version: '3'

networks:
  proxy:
    external: true

services:
  reverse-proxy:
    image: traefik:1.7-alpine # The official Traefik docker image
    command: '--api --docker'
    labels:
      - traefik.frontend.rule=Host:monitor.gmz2.work
      - traefik.port=8080
    ports:
      - 80:80     # The HTTP port
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json 
